{
 "title": "GlusterFS Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(gluster_up, job)" },
   {
    "name": "host",
    "label": "Host:",
    "query": "label_values(gluster_up, instance)"
   },
   {
    "name": "volume",
    "label": "volume",
    "query": "label_values(gluster_volume_status,volume)"
   }
  ]
 },
 "panels": [
  {
   "title": "GlusterFS Volume Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "gluster_node_size_total_bytes{instance=\"$host\",volume=\"$volume\"}-gluster_node_size_free_bytes{instance=\"$host\",volume=\"$volume\"}",
     "legendFormat": "node {{ hostname }}"
    }
   ]
  },
  {
   "title": "GlusterFS Volume Inodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_inodes_total{instance=\"$host\",volume=\"$volume\"}-node_inodes_free{instance=\"$host\",volume=\"$volume\"}",
     "legendFormat": "node {{ hostname }}"
    }
   ]
  },
  {
   "title": "GlusterFS Volume Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_volume_status{instance=\"$host\",volume=\"$volume\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "GlusterFS Volumes Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_volumes_count{instance=\"$host\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "GlusterFS Volume Writeable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_volume_writeable{instance=\"$host\"}",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "GlusterFS Brick Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_brick_count{instance=\"$host\",volume=\"$volume\"}",
     "legendFormat": "$volume bricks"
    }
   ]
  },
  {
   "title": "GlusterFS Heal files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_heal_info_files_count{instance=\"$host\",volume=\"$volume\"}",
     "legendFormat": "Heal Files count"
    }
   ]
  }
 ]
}